export const EventApiErrorCode = {
    BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
    BOOKING_NOT_OWNED: 'BOOKING_NOT_OWNED',
    BOOKING_NOT_CONFIRMED: 'BOOKING_NOT_CONFIRMED',
    EVENT_TIME_OUTSIDE_BOOKING: 'EVENT_TIME_OUTSIDE_BOOKING',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    SERVER_ERROR: 'SERVER_ERROR',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
} as const;