/*
  Warnings:

  - The values [BOOKING_CONFIRMATION,BOOKING_CANCELLATION,EVENT_REMINDER,EVVENT_REFUND_CONFIRMATION,EVENT_CANCELLATION,SPACE_REFUND_CONFIRMATION,EVENT_PAYOUT,SPACE_BOOKING_CONFIRMED,SPACE_BOOKING_CANCELLED,SPACE_BOOKING_PAYOUT] on the enum `EmailType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "EmailType_new" AS ENUM ('WELCOME', 'FORGOT_PASSWORD', 'ATTENDEE_BOOKING_CONFIRMATION', 'ATTENDEE_BOOKING_CANCELLATION', 'ATTENDEE_EVENT_REMINDER', 'ATTENDEE_REFUND_CONFIRMATION', 'HOST_BOOKING_CONFIRMATION', 'HOST_BOOKING_CANCELLATION', 'HOST_EVENT_CANCELLATION', 'HOST_REFUND_PROCESSED', 'HOST_EVENT_PAYOUT', 'VENDOR_SPACE_BOOKING_CONFIRMED', 'VENDOR_SPACE_BOOKING_CANCELLED', 'VENDOR_SPACE_PAYOUT');
ALTER TABLE "emails" ALTER COLUMN "type" TYPE "EmailType_new" USING ("type"::text::"EmailType_new");
ALTER TYPE "EmailType" RENAME TO "EmailType_old";
ALTER TYPE "EmailType_new" RENAME TO "EmailType";
DROP TYPE "public"."EmailType_old";
COMMIT;
